name: Nano Linux Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: sudo apt-get update && sudo apt-get install -y build-essential wget cpio python3 unzip rsync bc libncurses-dev

      - name: Clone Buildroot
        run: git clone --depth 1 https://github.com/buildroot/buildroot.git

      - name: Copy Config
        run: cp nano_defconfig buildroot/configs/nano_defconfig

      - name: Full Build
        run: |
          cd buildroot
          make nano_defconfig
          make

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: nano-os-images
          path: buildroot/output/images/
