name: Nano Linux Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential wget cpio python3 unzip rsync bc libncurses-dev
      - name: Build
        run: |
          git clone --depth 1 https://github.com/buildroot/buildroot.git
          cp nano_defconfig buildroot/configs/nano_defconfig
          cd buildroot
          make nano_defconfig
          make
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: nano-os-images
          path: buildroot/output/images/
